name: Award Application
description:  Award Application
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you? The model should be created by you, and we will verify this by checking the official model creator accounts on civitai.com or huggingface.com.
      placeholder: ex. twitter username or email or ...
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Award Category
      description: Which award category do you want to enter? Each applicant can only join with one model and one award categorie.
      options:
        - best anime trained
        - best anime merged
        - best anime lora
        - best anime lycoris
        - best anime textual inversion
        - best anime hypernetworks
        - best anime aesthetic gradient
        - best realistic trained
        - best realistic merged
        - best realistic lora
        - best realistic lycoris
        - best realistic textual inversion
        - best realistic hypernetworks
        - best realistic aesthetic gradient
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Official Creator's Public Model URL
      description: civitai or huggingface public url
      placeholder: ex. https://civitai.com/models/9668/plushies
    validations:
      required: true
  - type: textarea
    id: prompt1
    attributes:
      label: Enter the prompt 1 that will represent your model.
      description: Prompt 1 PNG Info (Please use AUTOMATIC1111/stable-diffusion-webui prompt standart. Generate your image with the webui, and then copy-paste the PNG info here.)
      placeholder: "beautiful human portrait Negative prompt: extra fingers, Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 10, Clip skip: 2, Model: model_name, Hires steps: 10, Hires upscale: 1.5 ..."
      render: shell
    validations:
      required: true
  - type: textarea
    id: prompt2
    attributes:
      label: Enter the prompt 2 that will represent your model.
      description: Prompt 2 PNG Info (Please use AUTOMATIC1111/stable-diffusion-webui prompt standart. Generate your image with the webui, and then copy-paste the PNG info here.)
      placeholder: "beautiful human portrait Negative prompt: extra fingers, Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 10, Clip skip: 2, Model: model_name, Hires steps: 10, Hires upscale: 1.5 ..."
      render: shell
    validations:
      required: true
  - type: textarea
    id: prompt3
    attributes:
      label: Enter the prompt 3 that will represent your model.
      description: Prompt 3 PNG Info (Please use AUTOMATIC1111/stable-diffusion-webui prompt standart. Generate your image with the webui, and then copy-paste the PNG info here.)
      placeholder: "beautiful human portrait Negative prompt: extra fingers, Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 10, Clip skip: 2, Model: model_name, Hires steps: 10, Hires upscale: 1.5 ..."
      render: shell
    validations:
      required: true
  - type: textarea
    id: prompt4
    attributes:
      label: Enter the prompt 4 that will represent your model.
      description: Prompt 4 PNG Info (Please use AUTOMATIC1111/stable-diffusion-webui prompt standart. Generate your image with the webui, and then copy-paste the PNG info here.)
      placeholder: "beautiful human portrait Negative prompt: extra fingers, Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 10, Clip skip: 2, Model: model_name, Hires steps: 10, Hires upscale: 1.5 ..."
      render: shell
    validations:
      required: true
  - type: textarea
    id: prompt5
    attributes:
      label: Enter the prompt 5 that will represent your model.
      description: Prompt 5 PNG Info (Please use AUTOMATIC1111/stable-diffusion-webui prompt standart. Generate your image with the webui, and then copy-paste the PNG info here.)
      placeholder: "beautiful human portrait Negative prompt: extra fingers, Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 10, Clip skip: 2, Model: model_name, Hires steps: 10, Hires upscale: 1.5 ..."
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Rules
      description: By submitting this issue, you agree to follow our [Rules & Eligibility](https://github.com/camenduru/awards/blob/main/README.md)
      options:
        - label: I agree to follow this project's Rules & Eligibility
          required: true
