name: Sponsorship Application
description: Sponsorship Application
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details (Please don't forget, your form will be public.)
      description: How can we get in touch with you?
      placeholder: ex. twitter username or email or discord username or ...
    validations:
      required: true
  - type: input
    id: sponsor_url
    attributes:
      label: Official Public Company URL 
      description: This URL will be used in our advertisement campaign.
      placeholder: ex. https://www.google.com
    validations:
      required: true
  - type: input
    id: sponsor_logo
    attributes:
      label: Official Public Logo URL 
      description: This Logo will be used in our advertisement campaign. (If you have it, please add the URL for the square logo.)
      placeholder: ex. https://www.placeholder.com/Logo_400x400.jpg
    validations:
      required: true
  - type: textarea
    id: sponsor_message
    attributes:
      label: If you have any message to the winners, please enter it here.
      description: This message will be shown under your name and logo within our advertisement campaign.
      placeholder: "Thank You! ❤"
    validations:
      required: false
  - type: textarea
    id: sponsor_offer
    attributes:
      label: Please enter what you can offer to the winners.
      description: Your offer should be specific.
      value: |
        - Best Anime Trained Model: 
        - Best Realistic Trained Model: 
        - Best Anime Merged Model: 
        - Best Realistic Merged Model: 
        - Best Anime LoRa Model: 
        - Best Realistic LoRa Model: 
        - Best Anime Lycoris Model: 
        - Best Realistic Lycoris Model: 
        - Best Anime Textual Inversion Model: 
        - Best Realistic Textual Inversion Model: 
        - Best Anime Hypernetworks Model: 
        - Best Realistic Hypernetworks Model: 
        - Best Anime Aesthetic Gradient Model: 
        - Best Realistic Aesthetic Gradient Model: 
    validations:
      required: true
  - type: textarea
    id: sponsor_category
    attributes:
      label: If you have any, please enter your categor(y)ies and what you can offer to the winner(s).
      description: Your offer should be specific.
      placeholder: "Best Architectural Trained Model: "
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Rules
      description: By submitting this form, you agree to follow our [Rules & Eligibility](https://github.com/camenduru/DiffusionAwards/blob/main/README.md)
      options:
        - label: I agree to follow this project's Rules & Eligibility
          required: true
  - type: markdown
    id: contact
    attributes:
      value: |
        **Contact**
        If you want, please contact with @camenduru [twitter](https://twitter.com/camenduru) or [discord](https://discord.com/users/616280178288623619) or diffusionawards@gmail.com
